### ISSUE TITLE
Parse error reading rules file .amidiminder/profile.rules and observed.rules

### ISSUE THREAD

**Issue by suedwestlicht** [mzero/midiminder#20]
It seems there are problems with the dot in "TSMIDI2.0". If I remove the dot between 2 and 0 then I get no error messages and the daemon starts.

```
Parse error on line 5: malformed address '"TSMIDI2.0":"MIDI 1"'
Parse error on line 6: malformed address '"TSMIDI2.0":"MIDI 1"'

```
The lines in profile.rules are:

```
"TSMIDI2.0":"MIDI 1" --> "Qtractor":"Master"
"TSMIDI2.0":"MIDI 1" --> "Qtractor":"Control"

```

**Comment by mzero** [comment]
Good catch! Turns out my fix for a different bug, fixed this one, too.

In the **upcoming** branch:
[bf6ad05 - handle parsing colons in exact match clients and ports](https://github.com/mzero/midiminder/commit/bf6ad05ce90908a378196d07f8fc379acb237ee3)
[185d274 - handle unparseable rules files on startup gracefully](https://github.com/mzero/midiminder/commit/185d274468be45e24617121a6e1f91a26f508b66)

I have added extra tests for your case to the **test.rules** file and will push that later today

**Comment by suedwestlicht** [comment]
Yep, it's fixed in the upcoming branch. Thx.
